name: retail_web_interface
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  cupertino_icons: ^1.0.2
  qr_bar_code_scanner_dialog: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/api.jpg

  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Medium.ttf

    - family: PortLligatSans
      fonts:
        - asset: fonts/PortLligatSans-Regular.ttf

    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf

# flutter run -d web-server --web-port 8080 --web-hostname 0.0.0.0
